### ISSUE TITLE
webpack.config.js has incorrect devserver 

### ISSUE THREAD

**Issue by mpchean** [DanWahlin/Getting-Started-With-TypeScript#1]
Devserver is missing, should be:
` devServer: {
      static: path.resolve(__dirname, 'dist'),
      port: 9000
   },`

**Comment by DanWahlin** [comment]
The project will run and load the browser without that actually. As long as the steps in the readme are followed (`npm install` and `npm start`) it should load right up on `http:localhost:8080`.

Having said that, if you're having a specific issue feel free to reopen this and provide details on the Node version, npm version, etc. that you're using.
